---

#EC2 CloudFormation template 

#Example:

AWSTemplateFormatVersion: "2020-04-23"
Description: A Simple EC2 instnce templat example
Reslources:
  MySimpleEC2:
    Type: AWS::EC2::instnce
    Properties:
      ImageId: ami-0dfff0sdsd78fj789
      InstanceType: t2.micro


